### ISSUE TITLE
New data feed for player contract and draft details

### ISSUE THREAD

**Issue by bradbarkhouse** [MySportsFeeds/mysportsfeeds-api#3]
A new feed will be introduced to v1.0 to list historical contract and draft info for each player, including:

Contract:
- start/end dates
- salary
- term
- No-Trade or other clauses
- bonuses

Draft:
- league & team
- when
- round
- selection

**Comment by mattjennings** [comment]
I'd love to see this.

**Comment by bradbarkhouse** [comment]
Been a while coming, but work for this is now officially underway!

**Comment by bradbarkhouse** [comment]
Code-related effort is completed.  Now it's just a matter of filling in all the data entry and documenting it in the API Docs.
