### ISSUE TITLE
Add Game Lineup data feed

### ISSUE THREAD

**Issue by bradbarkhouse** [MySportsFeeds/mysportsfeeds-api#6]
We already track starting lineups internally, but we'll be exposing that in  new data feed for v1.0 of the API.

**Comment by mbretag** [comment]
I think I'm right in saying this is still not available for NBA? It would be great to see added

**Comment by bradbarkhouse** [comment]
That's correct @mbretag , but it's becoming a highly requested feature, so will follow after our pending changes for filtering+sorting (also a huge feature).

We'll be implementing this across all league too btw, not just NBA.  So anyone looking for probable pitchers will be able to use this new feed to determine the starting lineup including pitcher.

**Comment by bradbarkhouse** [comment]
The new feed is now currently available as beta at:

[https://www.mysportsfeeds.com/api/feed/pull/mlb/2017-regular/game_startinglineup.json?gameid=20170525-SEA-WAS](https://www.mysportsfeeds.com/api/feed/pull/mlb/2017-regular/game_startinglineup.json?gameid=20170525-SEA-WAS)

We're actively creating the API docs section for it now.

**Comment by bradbarkhouse** [comment]
Done!
